language: node_js
script:
  - npm install lcov-server -g
  - npm run lint
  - npm run coverage
  - cat coverage/lcov.info | lcov-server-cli --url https://lcov-server.gabrielcsapo.com
node_js:
  - "6"
  - "8"
